###################################################################################################
#  BASEBAND PROCESSING MODULE CMAKELISTS
###################################################################################################

# This file contains the build directives for the baseband processing module

###################################################################################################
#  CHANGE LOG
###################################################################################################

# 7/23/26  Edward Speer  Initial Revision

###################################################################################################
#  BUILD DIRECTIVES
###################################################################################################

add_subdirectory(fpga)

