###################################################################################################
#  DIGIR SRC CMAKELISTS
###################################################################################################

# This CMake file fans out the build to the subdir of each module as needed

###################################################################################################
#  CHANGE LOG
###################################################################################################

# 7/23/26  Edward Speer  Initial revision

###################################################################################################
#  BUILD DIRECTIVES
###################################################################################################

add_subdirectory(BPM)

